#!/bin/bash
# WF 2020-06-03
python="python3"
backgound=""
log=""
while [  "$1" != ""  ]
do
  option="$1"
  case $option in
    -d|--debug)
      # show environment for debugging
      env
      ;;
    -p|--python)
      shift
      python="$1"
      ;;
    -b|--background)
      background="nohup " 
      logdir="/var/log/ormigrationtest"
      sudo mkdir -p $logdir
      me=$(whoami)
      sudo chown $me $logdir
      timestamp=$(date "+%Y-%m-%d-%H_%M_%S")
			log=$logdir/${timestamp}.log
			echo "test started $timestamp" >$log
      nohup $python -m unittest discover 2>&1 >>$log&
      exit 0
  esac
  shift
done
$python -m unittest discover